apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joviandss-pvc-rw-many
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: joviandss-sc

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistent-volume
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
              #runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  volumes:
    - name: persistent-volume
      persistentVolumeClaim:
        claimName: joviandss-pvc-rw-many
        readOnly: false


