apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-test
  storageClassName: joviandss-sc

