apiVersion: v1
kind: Pod
metadata:
  name: pv-test-pvc-nginx
spec:
  containers:
    - image: nginxinc/nginx-unprivileged
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: persistent-volume
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  volumes:
    - name: persistent-volume
      persistentVolumeClaim:
        claimName: pv-test-pvc 
        readOnly: false
