apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-jdss-pv
  labels:
    name: nginx-jdss-pv
spec:
  storageClassName: joviandss-persistent-volume-sc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: iscsi.csi.joviandss.open-e.com
    volumeHandle: testpv
