apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
  labels:
    name: pv-test
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: joviandss-nfs-sc
  csi:
    driver: nfs.csi.joviandss.open-e.com
    volumeHandle: vp_pv-test
    readOnly: false
