# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder "../configs", "/configs"
  config.vm.synced_folder "../src", "/src"

  config.vm.provider "virtualbox" do |vb|
    config.vm.network "public_network", bridge: "enp1s0f1"
    vb.memory = "4096"
    vb.cpus = "2"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
  end
end
